name: example-environment
channels:
  - conda-forge
  - jmcmurray
dependencies:
  - python
  - numpy
  - pandas
  - requests
  - folium
  - geopy
  - json
  - pip
  - pip:
    - matplotlib
    - lxml
    - geocoder
    - sklearn
